config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to:'rooms#top'

  get 'rooms/index'
  get "rooms/own_room" => "rooms#own_room"
  post "rooms/:id/reservations/recognize" => "reservations#recognize"
  get "rooms/:id/suggest" => "rooms#suggest"

  get "users/index" => "users#index"

  resources :users
  resources :rooms
  resources :reservations

  resources :rooms do
    resources :reservations
  end

  devise_scope :user do
    get 'account', to: 'users/registrations#account', as: 'account'
    patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
  end
end

app/views/shared/_error.html.erb
<div class="error_message">
  <% if resource.errors.any? %>
      <% resource.errors.full_messages.each do |message| %>
          <ul>
              <li><%= message %></li>
          </ul>
      <% end %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
      <a href="/"><img alt="サイトのロゴ画像" src="/assets/logo.png"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div id="navbar" class="navbar-collapse collapse">
        <div class="header">
        <div class="header_left">
        <i class="fas fa-map-marker-alt form1 d-none d-lg-block"></i>
        <%= search_form_for @q do |f| %>
            <%= f.text_field :address_cont, placeholder: 'エリア検索',class:"index_input form-control d-none d-lg-block " %>
        <% end %>
        <i class="fas fa-search form1 d-none d-lg-block"></i>
        <%= search_form_for @q do |f| %>
            <%= f.text_field :name_or_address_or_introduction_cont, placeholder: 'キーワード検索',class:"index_input form-control d-none d-lg-block " %>
        <% end %>
        </div>
    <div class="collapse navbar-collapse" id="navbarNav3">
      <ul class="nav navbar-nav navbar-right">
        <% if (!user_signed_in?) %>
            <li><%= link_to "ログイン", new_user_session_path, class: "btn btn-primary"  %></li>
            <li><%= link_to "登録", new_user_registration_path, class: "btn btn-secondary" %></li>
        <% else %>
        <li><%= current_user.email %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                  role="button" aria-haspopup="true" aria-expanded="false">
                <% if current_user.image? %>
                  <%= image_tag current_user.image.url ,:height=>"40", class:"usericon" %>
                <% else %>
                  <%= image_tag "default.png" ,:height=>"40" , class:"usericon" %>
                <% end %>
              </span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "ルーム一覧", rooms_index_path %></li>
              <li><%= link_to "ルーム登録", new_room_path %></li>
              <li><%= link_to "予約済みルーム一覧", reservations_path%></li>
              <li><%= link_to "登録済みルーム一覧", rooms_own_room_path %></li>
              <li><%= link_to "設定", "/users/show" %></li>
              <li><%= button_to "ログアウト", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
          <% end %>
        </ul>
    </div>
  </div>
</nav>