config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to:'rooms#top'

  get 'rooms/index'
  get "rooms/own_room" => "rooms#own_room"
  post "rooms/:id/reservations/recognize" => "reservations#recognize"
  get "rooms/:id/suggest" => "rooms#suggest"

  get "users/index" => "users#index"

  resources :users
  resources :rooms
  resources :reservations

  resources :rooms do
    resources :reservations
  end

  devise_scope :user do
    get 'account', to: 'users/registrations#account', as: 'account'
    patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user

  has_many :reservations, dependent: :destroy

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :address, presence: true
  validates :image, presence: true

  mount_uploader :image, ImageUploader

end

app/controllers/room_controller.rb
class RoomController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def listiong
  end

  def pricing
  end

  def description
  end

  def photo_upload
  end

  def location
  end

  def update
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
    @reservation = Reservation.new
  end

  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id
    if @room.save
      redirect_to room_path(@room)
    else
      render :new
    end
  end

  def show
    @room = Room.find(params[:id])
    @reservation = Reservation.new
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    @room.update(room_params)
    redirect_to room_path(@room)
  end

  def own_rooms
    @room = Room.find(params[:id])
    @own_room = @room.user_id == current_user.id
  end

  def suggest
    @room = Room.find(params[:id])
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    redirect_to rooms_index_path
  end

  private
  def room_params
    params.require(:room).permit(:name, :introduction, :price, :address, :image)
  end

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date, :member,  :total)
  end

end

app/helpers/room_helper.rb
module RoomHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<div class="create">
  <h3>ルーム編集</h3>
  <div class="errormesse">※全て入力必須</div> <br>
  <div class="create_form">

    <%= form_for @room do |f| %>

        <%= f.label :name ,class:"profile_label"%>
        <%= f.text_field :name ,class:"form-control  ", placeholder:"必須"%> <br>

        <%= f.label :address,class:"profile_label" %>
        <%= f.text_field :address,class:"form-control",placeholder:"必須" %> <br>

        <%= f.label :price ,class:"profile_label"%>
        <%= f.text_field :price,class:"form-control",placeholder:"必須" %> <br>

        <%= f.label :introduction,class:"profile_label" %>
        <%= f.text_area :introduction ,class:"form-control",placeholder:"必須",style:"height: 100px"%> <br>

        <%= f.label :image,class:"profile_label" %>
        <%= f.file_field :image,class:"form-control" %> <br>

        <p><small>現在のルーム画像</small></p>

          <% if @room.image? %>
            <%= image_tag @room.image.url,style:"height: 200px" %>
          <% else %>
            <%= image_tag '/default.png',style:"height: 200px"%>
          <% end %>



      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="room_index_view">

  <h2>ルーム一覧</h2>
  <p>検索結果： <%= @count %> </p>

  <div class="card-deck">
    <% @search_articles.each do |room| %>
        <div class="col-sm-6 col-lg-4 col-xl-3">
          <div class="card">
            <%= link_to room ,class:"card_link" do %>
              <% if room.image? %>
                <img src="<%= room.image %>" class="room_index_img">
              <% else %>
                <%= image_tag '/default.png', :class=>"room_index_img"%>
              <% end %>
              <div class="card-body">
                <h5 class="card-title"><%= room.name %></h5>
                <p class="card-text">  <%= simple_format room.introduction %></p>
                <p class="card-text">  <%= room.address %></p>
                <p class="card-text"> <%= number_to_currency(room.price, :unit => "円") %> / 日</p>
                <p class="card-text"><small class="text-muted">更新日: <%= room.updated_at.strftime('%Y月%m日%d日') %></small></p>

            </div>
            <% end %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="create">
  <h4>ルーム基本情報</h4>
    <div class="errormessage">※全て入力必須</div> <br>

  <div class="create_form">
  <%= render "shared/error", resource: @room %>
  <%= form_for @room do |f| %>
      <%= f.label :name ,class:"profile_label"%>
      <%= f.text_field :name ,class:"form-control ", placeholder:"必須"%>
      <%= f.label :address,class:"profile_label" %>
      <%= f.text_field :address,class:"form-control",placeholder:"必須" %>
      <%= f.label :price ,class:"profile_label"%>
      <%= f.text_field :price,class:"form-control",placeholder:"必須" %>
      <%= f.label :introduction,class:"profile_label" %>
      <%= f.text_area :introduction ,class:"form-control",placeholder:"必須"%>
      <%= f.label :image,class:"profile_label" %>
      <%= f.file_field :image,class:"form-control" %>
    </div>


    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
  </div>
</div>

app/views/rooms/own_room.html.erb
<div class="room_index_view">

  <h2><%= current_user.name %>様　マイルーム一覧</h2>

  <div class="card-deck">
    <% current_user.rooms.each do |room| %>
        <div class="col-sm-6 col-lg-4 col-xl-3">
          <div class="card">
            <%= link_to room ,class:"card_link" do %>
              <% if room.image? %>
                <img src="<%= room.image %>" class="room_index_img">
              <% else %>
                <%= image_tag '/default.png', :class=>"room_index_img"%>
              <% end %>
              <div class="card-body">
                <h5 class="card-title"><%= room.name %></h5>
                <p class="card-text">  <%= simple_format room.introduction %></p>
                <p class="card-text">  <%= room.address %></p>
                <p class="card-text"> <%= number_to_currency(room.price, :unit => "円") %> / 日</p>
                <p class="card-text"><small class="text-muted">更新日: <%= room.updated_at.strftime('%Y月%m日%d日') %></small></p>

            </div>
            <% end %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="room_show">
  <h1 fontsize="14">ルーム詳細・予約画面</h1>
  <div class="d-flex flex-wrap">
    <div class="col-lg-8 ">
      <div class="card ">
        <% if @room.image? %>
          <%= image_tag @room.image.url ,class:"room_show_img" %>
        <% else %>
          <%= image_tag '/default.png', class:"room_show_img"%>
        <% end %>
        <div class="card-body">
          <div class="card_title">
            <% if @room.user.image? %>
              <%= link_to "#{@room.id}/suggest" do %>
              <div class="room.user_page">
                <%= image_tag @room.user.image.url, :height=>"40", class:"usericon" %><br>
                <%= @room.user.name %>
              </div>
              <% end %>
            <% else %>
              <div class="room.user_page">
                <%= link_to (@room.user) do %>
                  <%= image_tag "default.png" ,:height=>"40" , class:"usericon" %>
                  <%= @room.user.name %>
                <% end %>
              </div>
            <% end %>
            <div class="room_show_name">
              <h4 class="card-title"><%= @room.name %></h5>
              <font size="2",class="card-text",fornsize="2"><%= @room.address %></font><br>
            </div>
          </div>
          <hr size=".5px" color="#bbb">
          <p class="card-text">  <%= simple_format @room.introduction %></p>
        </div>
      </div>
    </div>
    <div class="col-lg-4">
      <div class="room_show_container">
        <%# ここから予約画面へ飛ばすフォーム %>
        <%= form_for @reservation ,url: "/rooms/#{@room.id}/reservations/recognize" do |f| %>
        <%= render "shared/error",resource: @reservation %>
          Room.price<%= @price %>
          <h5>
            <%= number_to_currency(@room.price, :unit => "円") %> / 1人あたり1泊
          </h5>
            <hr size=".5px" color="#bbb">
          <div class="form-group">
              <%= f.label :start_date%>
              <%= f.date_field :start_date ,class:"profile_textfield form-control",value: Time.now.strftime("%Y-%m-%d") %>
              <%= f.label :end_date%>
              <%= f.date_field :end_date ,class:"profile_textfield form-control",value: Time.now.tomorrow.strftime("%Y-%m-%d") %>
              <%= f.label :member%>
              <%= f.number_field :member ,class:"profile_textfield form-control",value: 1 %>
              <br>
            <% if user_signed_in? %>
              <button type="submit" class="btn btn-primary">予約確認へ進む</button>
            <% else %>
              <div class="edit_btn">
              <%= link_to("ログイン",new_user_session_path) %>
              </div>
            <% end %>
          </div>
        <% end %>
        <%# ここまで予約画面へ飛ばすフォーム %>
        <% if user_signed_in? && @room.user.id == current_user.id %>
          <%= link_to"編集", edit_room_path(@room) ,class:"btn btn-primary"%>
          <%= button_to "削除", room_path(@room), method: :delete, data: { confirm: "本当に削除しますか？" } , class:"btn btn-primary"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/suggest.html.erb
 <div class="profile_container">
  <div class="create">
    <h3>管理者プロフィール</h3>
    <hr size=".5px" color="#bbb">

    <div class="create_form">
        <div class="form-group">
          <div class="posts_tbody">
            <% if @room.user.image? %>
              <div class="room.user_page">
                <%= image_tag @room.user.image.url,class:"room_show_img" %><br>
              </div>
            <% else %>
              <div class="room.user_page">
                  <%= image_tag "default.png",class:"room_show_img" %>
              </div>
            <% end %>
            <br><br>
            <h6>ホスト名：<%= @room.user.name %> <br><br></h6>
            <h6>自己紹介：<%= @room.user.introduction %> <br><br></h6>

            <div class="edit_btn">
              <%= link_to("戻る",room_path)%>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/top.html.erb
<div class="head">
  <div class="form-area">
    <p class="form-area-title mb-4">Potepan Shareでまだ体験したことのない旅をしよう</p>
      <label for="___">エリア</label>
      <%= search_form_for @q do |f| %>
        <%= f.text_field :address_cont,placeholder: '東京',class:"form-control" %>
        <%= f.submit "検索" ,class:"btn btn-primary"%>
      <% end %>
  </div>
</div>

<div class="container">
  <div class="top_area_container m-5 ">
    <h2>おすすめのエリア</h2>

    <div class="row">
      <div class="top_area_img col-lg-3 col-6">
        <%= link_to image_tag("img_tokyo.jpg"), rooms_index_path(q: { address_cont: '東京' })%>
        <span>東京</span>
      </div>
      <div class="top_area_img col-lg-3 col-6">
        <%= link_to image_tag("img_osaka.jpg"), rooms_index_path(q: { address_cont: '大阪' })%>
        <span>大阪</span>
      </div>
      <div class="top_area_img col-lg-3 col-6">
        <%= link_to image_tag("img_kyoto.jpg"), rooms_index_path(q: { address_cont: '京都' })%>
        <span>京都</span>
      </div>
      <div class="top_area_img col-lg-3 col-6">
        <%= link_to image_tag("img_sapporo.jpg"), rooms_index_path(q: { address_cont: '北海道' })%>
        <span>北海道</span>
      </div>
    </div>
  </div>
</div>